
Standard Augmentation!
Traceback (most recent call last):
  File "/home/yu-jw19/venom/project2/train.py", line 573, in <module>
    main()
  File "/home/yu-jw19/venom/project2/train.py", line 286, in main
    EmotionDataset('/data/emotion.csv',transform=transform_train, train=True),
  File "/home/yu-jw19/venom/project2/dataset.py", line 18, in __init__
    self.data = pd.read_csv(root)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/data/emotion.csv'
Traceback (most recent call last):
  File "/home/yu-jw19/venom/project2/train.py", line 573, in <module>
    main()
  File "/home/yu-jw19/venom/project2/train.py", line 286, in main
    EmotionDataset('/data/emotion.csv',transform=transform_train, train=True),
  File "/home/yu-jw19/venom/project2/dataset.py", line 18, in __init__
    self.data = pd.read_csv(root)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/data/emotion.csv'