
Standard Augmentation!
/home/yu-jw19/venom/project2/dataset.py:25: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  self.target = target[np.where(self.data[:,-1]=='Training')].reshape(-1,1)
Number of final features: 64
Number of model parameters: 466711
/home/yu-jw19/venom/project2/dataset.py:28: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  self.target = target[np.where(self.data[:,-1]=='Test')].reshape(-1,1)
Traceback (most recent call last):
  File "/home/yu-jw19/venom/project2/train.py", line 576, in <module>
    main()
  File "/home/yu-jw19/venom/project2/train.py", line 403, in main
    train_metrics = train(train_loader, model, ce_criterion, optimizer, epoch)
  File "/home/yu-jw19/venom/project2/train.py", line 437, in train
    for i, (x, target) in enumerate(train_loader):
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yu-jw19/venom/project2/dataset.py", line 32, in __getitem__
    img, target = self.train_data[index], self.train_target[index]
AttributeError: 'EmotionDataset' object has no attribute 'train_data'
Traceback (most recent call last):
  File "/home/yu-jw19/venom/project2/train.py", line 576, in <module>
    main()
  File "/home/yu-jw19/venom/project2/train.py", line 403, in main
    train_metrics = train(train_loader, model, ce_criterion, optimizer, epoch)
  File "/home/yu-jw19/venom/project2/train.py", line 437, in train
    for i, (x, target) in enumerate(train_loader):
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yu-jw19/venom/project2/dataset.py", line 32, in __getitem__
    img, target = self.train_data[index], self.train_target[index]
AttributeError: 'EmotionDataset' object has no attribute 'train_data'