2021-11-21 22:14:26,550 INFO    MainThread:83014 [internal.py:wandb_internal():87] W&B internal server running at pid: 83014, started at: 2021-11-21 22:14:26.550059
2021-11-21 22:14:26,552 DEBUG   HandlerThread:83014 [handler.py:handle_request():130] handle_request: check_version
2021-11-21 22:14:26,553 INFO    WriterThread:83014 [datastore.py:open_for_write():77] open: /home/yu-jw19/venom/project2/wandb/run-20211121_221426-3nk1lfqm/run-3nk1lfqm.wandb
2021-11-21 22:14:26,555 DEBUG   SenderThread:83014 [sender.py:send():238] send: header
2021-11-21 22:14:26,555 DEBUG   SenderThread:83014 [sender.py:send_request():252] send_request: check_version
2021-11-21 22:14:27,345 DEBUG   SenderThread:83014 [sender.py:send():238] send: run
2021-11-21 22:14:27,854 INFO    SenderThread:83014 [dir_watcher.py:__init__():169] watching files in: /home/yu-jw19/venom/project2/wandb/run-20211121_221426-3nk1lfqm/files
2021-11-21 22:14:27,855 INFO    SenderThread:83014 [sender.py:_start_run_threads():825] run started: 3nk1lfqm with start time 1637504066
2021-11-21 22:14:27,855 DEBUG   SenderThread:83014 [sender.py:send():238] send: summary
2021-11-21 22:14:27,855 INFO    SenderThread:83014 [sender.py:_save_file():960] saving file wandb-summary.json with policy end
2021-11-21 22:14:27,856 DEBUG   HandlerThread:83014 [handler.py:handle_request():130] handle_request: run_start
2021-11-21 22:14:27,861 DEBUG   HandlerThread:83014 [meta.py:__init__():40] meta init
2021-11-21 22:14:27,861 DEBUG   HandlerThread:83014 [meta.py:__init__():54] meta init done
2021-11-21 22:14:27,861 DEBUG   HandlerThread:83014 [meta.py:probe():214] probe
2021-11-21 22:14:27,868 DEBUG   HandlerThread:83014 [meta.py:_setup_git():204] setup git
2021-11-21 22:14:27,888 DEBUG   HandlerThread:83014 [meta.py:_setup_git():211] setup git done
2021-11-21 22:14:27,888 DEBUG   HandlerThread:83014 [meta.py:_save_pip():58] save pip
2021-11-21 22:14:27,889 DEBUG   HandlerThread:83014 [meta.py:_save_pip():72] save pip done
2021-11-21 22:14:27,889 DEBUG   HandlerThread:83014 [meta.py:probe():252] probe done
2021-11-21 22:14:27,895 DEBUG   SenderThread:83014 [sender.py:send():238] send: files
2021-11-21 22:14:27,895 INFO    SenderThread:83014 [sender.py:_save_file():960] saving file wandb-metadata.json with policy now
2021-11-21 22:14:27,905 DEBUG   HandlerThread:83014 [handler.py:handle_request():130] handle_request: stop_status
2021-11-21 22:14:27,905 DEBUG   SenderThread:83014 [sender.py:send_request():252] send_request: stop_status
2021-11-21 22:14:28,384 DEBUG   SenderThread:83014 [sender.py:send():238] send: config
2021-11-21 22:14:28,384 DEBUG   SenderThread:83014 [sender.py:send():238] send: metric
2021-11-21 22:14:28,385 DEBUG   SenderThread:83014 [sender.py:send():238] send: metric
2021-11-21 22:14:28,858 INFO    Thread-8  :83014 [dir_watcher.py:_on_file_created():217] file/dir created: /home/yu-jw19/venom/project2/wandb/run-20211121_221426-3nk1lfqm/files/output.log
2021-11-21 22:14:28,858 INFO    Thread-8  :83014 [dir_watcher.py:_on_file_created():217] file/dir created: /home/yu-jw19/venom/project2/wandb/run-20211121_221426-3nk1lfqm/files/wandb-summary.json
2021-11-21 22:14:28,859 INFO    Thread-8  :83014 [dir_watcher.py:_on_file_created():217] file/dir created: /home/yu-jw19/venom/project2/wandb/run-20211121_221426-3nk1lfqm/files/requirements.txt
2021-11-21 22:14:28,859 INFO    Thread-8  :83014 [dir_watcher.py:_on_file_created():217] file/dir created: /home/yu-jw19/venom/project2/wandb/run-20211121_221426-3nk1lfqm/files/wandb-metadata.json
2021-11-21 22:14:28,900 INFO    Thread-11 :83014 [upload_job.py:push():137] Uploaded file /tmp/tmp_66y3b2uwandb/yaqt670h-wandb-metadata.json
2021-11-21 22:14:30,857 INFO    Thread-8  :83014 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/yu-jw19/venom/project2/wandb/run-20211121_221426-3nk1lfqm/files/output.log
2021-11-21 22:14:43,413 DEBUG   HandlerThread:83014 [handler.py:handle_request():130] handle_request: stop_status
2021-11-21 22:14:43,414 DEBUG   SenderThread:83014 [sender.py:send_request():252] send_request: stop_status
2021-11-21 22:14:55,876 INFO    Thread-8  :83014 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/yu-jw19/venom/project2/wandb/run-20211121_221426-3nk1lfqm/files/output.log
2021-11-21 22:14:56,328 DEBUG   SenderThread:83014 [sender.py:send():238] send: stats
2021-11-21 22:14:57,815 ERROR   SenderThread:83014 [internal_api.py:execute():144] 409 response executing GraphQL.
2021-11-21 22:14:57,816 ERROR   SenderThread:83014 [internal_api.py:execute():145] {"errors":[{"message":"Error 1062: Duplicate entry '557039-3nk1lfqm' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2021-11-21 22:14:58,329 INFO    WriterThread:83014 [datastore.py:close():281] close: /home/yu-jw19/venom/project2/wandb/run-20211121_221426-3nk1lfqm/run-3nk1lfqm.wandb
2021-11-21 22:14:58,336 INFO    HandlerThread:83014 [handler.py:finish():731] shutting down handler
2021-11-21 22:14:58,593 ERROR   MainThread:83014 [internal.py:wandb_internal():158] Thread SenderThread:
Traceback (most recent call last):
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 1298, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 147, in execute
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 141, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 52, in run
    self._run()
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 96, in _run
    self._debounce()
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/sdk/internal/internal.py", line 297, in _debounce
    self._sm.debounce()
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 319, in debounce
    self._debounce_config()
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 325, in _debounce_config
    self._api.upsert_run(
  File "/home/yu-jw19/.local/lib/python3.9/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    raise CommError(err.response, err)
wandb.errors.CommError: <Response [409]>
2021-11-21 22:14:59,881 INFO    Thread-8  :83014 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/yu-jw19/venom/project2/wandb/run-20211121_221426-3nk1lfqm/files/output.log
2021-11-21 22:15:00,619 INFO    MainThread:83014 [internal.py:handle_exit():77] Internal process exited
